"use client";
import { useCallback, useEffect, useState } from "react";
import { ClipboardCheck, Plus, RefreshCw } from "lucide-react";
import { useAppWorkspace } from "@/components/app/AppWorkspaceContext";
import { createAgent, createBusinessReview, createDecision, createProposal, evaluateAgent, listPhase2, reviewProposal, updateDecision, type Phase2Kind } from "@/lib/api/insightmend";

const tabs: Array<{ key: Phase2Kind; label: string }> = [{key:"decisions",label:"Decision Workbench"},{key:"proposals",label:"Change proposals"},{key:"agents",label:"Signal Agents"},{key:"reviews",label:"Business Reviews"}];

export default function DecisionsPage() {
 const { activeWorkspace } = useAppWorkspace(); const wid = activeWorkspace.workspace_id;
 const [tab,setTab]=useState<Phase2Kind>("decisions"); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await listPhase2(tab,wid));}catch(e){setError(e instanceof Error?e.message:"Unable to load.");}finally{setLoading(false);}},[tab,wid]);
 useEffect(()=>{void load();},[load]);
 async function add(){try{if(tab==="decisions") await createDecision({workspace_id:wid,title:"New governed decision",recommendation:"Define the evidence-backed action, owner, target, and review date."}); if(tab==="proposals") await createProposal({workspace_id:wid,entity_type:"metric",title:"Governed metric improvement",rationale:"Proposed from observed analytical demand.",before_state:{},proposed_state:{status:"candidate"},impact_analysis:{requires_validation:true}}); if(tab==="agents") await createAgent({workspace_id:wid,name:"Metric threshold monitor",metric_name:"revenue",condition:"below",threshold:0,schedule:"daily"}); if(tab==="reviews") await createBusinessReview({workspace_id:wid,title:`Business Review · ${new Date().toLocaleDateString()}`}); await load();}catch(e){setError(e instanceof Error?e.message:"Creation failed.");}}
 return <main className="min-h-screen bg-slate-50 p-6 dark:bg-[#070810] dark:text-white"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-600">InsightMend Decision Operations</p><h1 className="mt-2 text-3xl font-semibold">From evidence to accountable outcomes</h1><p className="mt-2 text-sm text-slate-500">Govern changes, monitor signals, assign decisions, and measure results.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border bg-white p-2.5 dark:border-white/10 dark:bg-white/5"><RefreshCw className="h-4 w-4"/></button><button onClick={()=>void add()} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white dark:bg-white dark:text-slate-950"><Plus className="h-4 w-4"/>Create</button></div></header>
 <nav className="mt-8 flex gap-2 overflow-x-auto">{tabs.map(t=><button key={t.key} onClick={()=>setTab(t.key)} className={`rounded-xl px-4 py-2 text-sm font-medium ${tab===t.key?"bg-slate-950 text-white dark:bg-white dark:text-slate-950":"bg-white text-slate-500 dark:bg-white/5"}`}>{t.label}</button>)}</nav>
 {error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}
 {loading?<p className="mt-12 text-center text-sm text-slate-500">Loading decision operations…</p>:items.length?<div className="mt-6 grid gap-4 lg:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/[.04]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-violet-600">{tab.slice(0,-1)}</p><h2 className="mt-1 font-semibold">{item.title||item.name}</h2></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold dark:bg-white/10">{item.status||((item.last_result||{}).triggered?"triggered":"ready")}</span></div>
 <p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.recommendation||item.rationale||(tab==="agents"?`${item.metric_name} ${item.condition} ${item.threshold}`:"Recurring governed operating review")}</p>
 {tab==="decisions"?<div className="mt-4 flex gap-2"><button onClick={async()=>{await updateDecision(item.id,{status:"in_progress"});await load();}} className="rounded-lg bg-violet-600 px-3 py-1.5 text-xs font-semibold text-white">Start</button><button onClick={async()=>{await updateDecision(item.id,{status:"completed"});await load();}} className="rounded-lg border px-3 py-1.5 text-xs font-semibold dark:border-white/10">Complete</button></div>:null}
 {tab==="proposals"&&item.status==="pending_review"?<div className="mt-4 flex gap-2"><button onClick={async()=>{await reviewProposal(item.id,"approved");await load();}} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">Approve</button><button onClick={async()=>{await reviewProposal(item.id,"rejected");await load();}} className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Reject</button></div>:null}
 {tab==="agents"?<button onClick={async()=>{const value=Number(window.prompt("Current governed metric value"));if(Number.isFinite(value)){await evaluateAgent(item.id,value,item.last_value);await load();}}} className="mt-4 rounded-lg bg-cyan-600 px-3 py-1.5 text-xs font-semibold text-white">Evaluate now</button>:null}
 {tab==="reviews"?<div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Stat label="Open" value={(item.summary?.open_decisions||[]).length}/><Stat label="Completed" value={(item.summary?.completed_decisions||[]).length}/><Stat label="Signals" value={(item.summary?.triggered_signals||[]).length}/></div>:null}
 </article>)}</div>:<div className="mt-14 rounded-3xl border border-dashed p-12 text-center text-slate-500"><ClipboardCheck className="mx-auto h-8 w-8"/><p className="mt-3 text-sm">No records yet. Create the first governed {tab.slice(0,-1)}.</p></div>}
 </div></main>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-white/5"><strong className="block text-lg text-slate-900 dark:text-white">{value}</strong><span className="text-slate-500">{label}</span></div>}
