"use client";
import {useCallback,useEffect,useState} from "react";
import {Blocks,Plus,RefreshCw} from "lucide-react";
import {useAppWorkspace} from "@/components/app/AppWorkspaceContext";
import {createPlatform,listPlatform,type PlatformKind} from "@/lib/api/insightmendPlatform";
const tabs:Array<{key:PlatformKind;label:string}>=[{key:"channels",label:"Delivery"},{key:"schedules",label:"Schedules"},{key:"embeds",label:"Embeds"},{key:"attachments",label:"Attachments"},{key:"imports",label:"Semantic imports"},{key:"outbox",label:"Delivery log"}];
export default function PlatformPage(){const {activeWorkspace}=useAppWorkspace();const wid=activeWorkspace.workspace_id;const [tab,setTab]=useState<PlatformKind>("channels");const [items,setItems]=useState<any[]>([]);const [error,setError]=useState<string|null>(null);const load=useCallback(async()=>{try{setError(null);setItems(await listPlatform(tab,wid));}catch(e){setError(e instanceof Error?e.message:"Unable to load")}},[tab,wid]);useEffect(()=>{void load()},[load]);
async function add(){try{if(tab==="channels"){const url=window.prompt("HTTPS webhook URL for Slack, Teams, or your service");if(url)await createPlatform("channels",{workspace_id:wid,name:"Collaboration delivery",channel_type:"webhook",config:{webhook_url:url}})}else if(tab==="embeds")await createPlatform("embeds",{workspace_id:wid,name:"Customer analytics app",allowed_origins:[]});else if(tab==="attachments"){const content=window.prompt("Paste CSV content (up to 1 MB)");if(content)await createPlatform("attachments",{workspace_id:wid,filename:"analysis.csv",mime_type:"text/csv",content_text:content})}else if(tab==="imports"){const content=window.prompt("Paste MetricFlow YAML for governed review");if(content)await createPlatform("imports",{workspace_id:wid,source_type:"metricflow",content})}else if(tab==="schedules"){setError("Create a delivery channel first, then schedule a dashboard or Business Review through the API.");return}await load()}catch(e){setError(e instanceof Error?e.message:"Creation failed")}}
return <main className="min-h-screen bg-slate-50 p-6 dark:bg-[#070810] dark:text-white"><div className="mx-auto max-w-7xl"><header className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-600">InsightMend Platform</p><h1 className="mt-2 text-3xl font-semibold">Distribute governed intelligence</h1><p className="mt-2 text-sm text-slate-500">Delivery, embedding, attachments, exploration, and semantic interoperability.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border bg-white p-2.5 dark:border-white/10 dark:bg-white/5"><RefreshCw className="h-4 w-4"/></button>{!['outbox'].includes(tab)?<button onClick={()=>void add()} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white dark:bg-white dark:text-slate-950"><Plus className="h-4 w-4"/>Configure</button>:null}</div></header><nav className="mt-8 flex gap-2 overflow-auto">{tabs.map(t=><button key={t.key} onClick={()=>setTab(t.key)} className={`rounded-xl px-4 py-2 text-sm font-medium ${tab===t.key?'bg-slate-950 text-white dark:bg-white dark:text-slate-950':'bg-white text-slate-500 dark:bg-white/5'}`}>{t.label}</button>)}</nav>{error?<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{error}</div>:null}<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(i=><article key={i.id} className="rounded-2xl border bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/[.04]"><p className="text-[10px] font-semibold uppercase tracking-wider text-cyan-600">{tab.slice(0,-1)}</p><h2 className="mt-2 font-semibold">{i.name||i.filename||i.source_ref||i.status}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{i.channel_type||i.artifact_type||i.mime_type||i.source_type||`Status: ${i.status}`}</p><span className="mt-4 inline-block rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-semibold text-emerald-700">{i.status||'configured'}</span></article>)}</div>{!items.length?<div className="mt-14 rounded-3xl border border-dashed p-12 text-center text-slate-500"><Blocks className="mx-auto h-8 w-8"/><p className="mt-3 text-sm">No {tab} configured yet.</p></div>:null}</div></main>}
